name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/azure-static-web-apps-ashy-sky-09ddfcc00.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/azure-static-web-apps-ashy-sky-09ddfcc00.yml'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SKY_09DDFCC00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/website" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          PD_PHISHING_API_BASE: ${{ secrets.PD_PHISHING_API_BASE }}
          PD_SEVICE_ID: ${{ secrets.PD_SEVICE_ID }}
          PD_TEMPLATE_ID: ${{ secrets.PD_TEMPLATE_ID }}
          PD_PUBLIC_KEY: ${{ secrets.PD_PUBLIC_KEY }}
          PD_CAPCHA_SITE_KEY: ${{ secrets.PD_CAPCHA_SITE_KEY }}
          PD_CHROME_EXTENSION_URL: https://chromewebstore.google.com/detail/phishdetectnet/dookehinampeonmbhebhacbbempjjala

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SKY_09DDFCC00 }}
          action: "close"
