name: Trigger auto deployment for phishing-model-api-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'app/**'
    - '.github/workflows/phishing-model-api-app-AutoDeployTrigger-0955bcd2-dd27-4920-9202-66b1dae8964d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PHISHINGMODELAPIAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PHISHINGMODELAPIAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PHISHINGMODELAPIAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: app/Dockerfile
          registryUrl: ${{ secrets.PHISHINGMODELAPIAPP_REGISTRY_NAME }}.azurecr.io
          registryUsername: ${{ secrets.PHISHINGMODELAPIAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PHISHINGMODELAPIAPP_REGISTRY_PASSWORD }}
          containerAppName: phishing-model-api-app
          resourceGroup: phishing-model-api-rg
          imageToBuild: default/phishing-model-api-app:${{ github.sha }}


